[tool.poetry]
name = "{{ cookiecutter.project_slug }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.project_short_description }}"
authors = ["{{ cookiecutter.full_name.replace("\"", "\\\"") }} <{{ cookiecutter.email }}>"]
{%- set license_classifiers = {
    "MIT license": "MIT",
    "Apache Software License 2.0": "Apache-2.0",
    "GNU General Public License v3.0": "GPL-3.0-only",
    "GNU General Public License v2.0": "GPL-2.0-only",
    "BSD 3-Clause 'New' or 'Revised' License": "BSD-3-Clause",
    "GNU Lesser General Public License v2.1": "LGPL-2.1-only",
    "BSD 2-Clause 'Simplified' License": "BSD-2-Clause",
} %}
{%- if cookiecutter.open_source_license in license_classifiers %}
license = "{{ license_classifiers[cookiecutter.open_source_license] }}"
{%- endif %}
readme = "README.md"
keywords = []
repository = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}/issues"
"Source" = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}"
{% if cookiecutter.create_docs == "y" -%}"Documentation" = "https://{{ cookiecutter.project_slug }}.readthedocs.io"{% endif %}

[tool.poetry.dependencies]
python = "^3.7.1"
tqdm = "^4.56.0"
importlib-metadata = "^4.5.0;python_version<3.8"
sphinx = {version = "^4.0.2", optional = true}
insegel = {version = "^1.1.0", optional = true}
{%- if cookiecutter.data_science == "y" -%}
scikit-learn = "^0.24.1"
pandas = "^1.2.1"
joblib = "^1.0.0"
numpy = "^1.20.0"
scipy = "^1.6.0"
{%- endif %}


[tool.poetry.dev-dependencies]
ipdb = "^0.13.4"
mypy = "^0.800"
darglint = "^1.6.0"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
tox = "^3.21.4"
black = "^21.6b0"
pyproject-flake8 = "^0.0.1-alpha.2"
flake8-eradicate = "^1.0.0"
flake8-isort = "^4.0.0"
flake8-docstrings = "^1.6.0"
flake8-debugger = "^4.0.0"
flake8-comprehensions = "^3.5.0"
flake8-print = "^4.0.0"
flake8-bugbear = "^21.4.3"
flake8-simplify = "^0.14.1"
{%- if cookiecutter.command_line_interface == "y" -%}
typer = "^0.3.2"
{% endif %}


[tool.poetry.extras]
docs = ["sphinx", "insegel"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
ignore = "E203, E266, E501, W503, F403, F401, B950"
max-line-length = 88
max-complexity = 18
select = "B,C,E,F,W,T4,B9"
count = "true"
show-source = "true"
statistics = "true"

[tool.black]
line-length = 88
experimental-string-processing = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
